ALTER TABLE ModelSkill
ADD FOREIGN KEY (ModelID) REFERENCES Model(ModelID) ON DELETE CASCADE
GO

ALTER TABLE ModelSkill
ADD FOREIGN KEY (SkillID) REFERENCES Skills(SkillID) ON DELETE CASCADE
GO

ALTER TABLE ModelLanguage
ADD FOREIGN KEY (ModelID) REFERENCES Model(ModelID) ON DELETE CASCADE
GO

ALTER TABLE ModelLanguage
ADD FOREIGN KEY (LanguageID) REFERENCES Language(LanguageID) ON DELETE CASCADE
GO

ALTER TABLE ModelContract
ADD FOREIGN KEY (ModelID) REFERENCES Model(ModelID) ON DELETE CASCADE
GO

ALTER TABLE ModelContract
ADD FOREIGN KEY (ContractID) REFERENCES Contract(ContractID) ON DELETE CASCADE
GO

ALTER TABLE Contract
ADD FOREIGN KEY (CusID) REFERENCES Customer(CusID) ON DELETE CASCADE
GO

ALTER TABLE ModelImg
ADD FOREIGN KEY (ModelID) REFERENCES Model(ModelID) ON DELETE CASCADE
GO
